# Replace this file with your own paths!

# relative path to where data is saved
data_dir:
  gesture: "~/Projects/BSN2025/LearnedSampling/datasets/raw_data/gestures-dataset/gestures-dataset"
  gesture_impair: "~/Projects/BSN2025/LearnedSampling/datasets/raw_data/gesture_impair"

# relative path to where models, logs, and checkpoints will be saved
model_dir: "."